//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DEMO.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://us_minhquang.com/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback addBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback getListBookOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::DEMO.Properties.Settings.Default.DEMO_localhost_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event addBookCompletedEventHandler addBookCompleted;
        
        /// <remarks/>
        public event updateBookCompletedEventHandler updateBookCompleted;
        
        /// <remarks/>
        public event deleteBookCompletedEventHandler deleteBookCompleted;
        
        /// <remarks/>
        public event searchBookCompletedEventHandler searchBookCompleted;
        
        /// <remarks/>
        public event getListBookCompletedEventHandler getListBookCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://us_minhquang.com/HelloWorld", RequestNamespace="http://us_minhquang.com/", ResponseNamespace="http://us_minhquang.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://us_minhquang.com/addBook", RequestNamespace="http://us_minhquang.com/", ResponseNamespace="http://us_minhquang.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool addBook(string ma, string ten, string sl, string gia) {
            object[] results = this.Invoke("addBook", new object[] {
                        ma,
                        ten,
                        sl,
                        gia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void addBookAsync(string ma, string ten, string sl, string gia) {
            this.addBookAsync(ma, ten, sl, gia, null);
        }
        
        /// <remarks/>
        public void addBookAsync(string ma, string ten, string sl, string gia, object userState) {
            if ((this.addBookOperationCompleted == null)) {
                this.addBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddBookOperationCompleted);
            }
            this.InvokeAsync("addBook", new object[] {
                        ma,
                        ten,
                        sl,
                        gia}, this.addBookOperationCompleted, userState);
        }
        
        private void OnaddBookOperationCompleted(object arg) {
            if ((this.addBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addBookCompleted(this, new addBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://us_minhquang.com/updateBook", RequestNamespace="http://us_minhquang.com/", ResponseNamespace="http://us_minhquang.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool updateBook(string ma, string ten, string sl, string gia) {
            object[] results = this.Invoke("updateBook", new object[] {
                        ma,
                        ten,
                        sl,
                        gia});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void updateBookAsync(string ma, string ten, string sl, string gia) {
            this.updateBookAsync(ma, ten, sl, gia, null);
        }
        
        /// <remarks/>
        public void updateBookAsync(string ma, string ten, string sl, string gia, object userState) {
            if ((this.updateBookOperationCompleted == null)) {
                this.updateBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateBookOperationCompleted);
            }
            this.InvokeAsync("updateBook", new object[] {
                        ma,
                        ten,
                        sl,
                        gia}, this.updateBookOperationCompleted, userState);
        }
        
        private void OnupdateBookOperationCompleted(object arg) {
            if ((this.updateBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateBookCompleted(this, new updateBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://us_minhquang.com/deleteBook", RequestNamespace="http://us_minhquang.com/", ResponseNamespace="http://us_minhquang.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool deleteBook(string ma) {
            object[] results = this.Invoke("deleteBook", new object[] {
                        ma});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void deleteBookAsync(string ma) {
            this.deleteBookAsync(ma, null);
        }
        
        /// <remarks/>
        public void deleteBookAsync(string ma, object userState) {
            if ((this.deleteBookOperationCompleted == null)) {
                this.deleteBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteBookOperationCompleted);
            }
            this.InvokeAsync("deleteBook", new object[] {
                        ma}, this.deleteBookOperationCompleted, userState);
        }
        
        private void OndeleteBookOperationCompleted(object arg) {
            if ((this.deleteBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteBookCompleted(this, new deleteBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://us_minhquang.com/searchBook", RequestNamespace="http://us_minhquang.com/", ResponseNamespace="http://us_minhquang.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SachDTO searchBook(string ma) {
            object[] results = this.Invoke("searchBook", new object[] {
                        ma});
            return ((SachDTO)(results[0]));
        }
        
        /// <remarks/>
        public void searchBookAsync(string ma) {
            this.searchBookAsync(ma, null);
        }
        
        /// <remarks/>
        public void searchBookAsync(string ma, object userState) {
            if ((this.searchBookOperationCompleted == null)) {
                this.searchBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchBookOperationCompleted);
            }
            this.InvokeAsync("searchBook", new object[] {
                        ma}, this.searchBookOperationCompleted, userState);
        }
        
        private void OnsearchBookOperationCompleted(object arg) {
            if ((this.searchBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchBookCompleted(this, new searchBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://us_minhquang.com/getListBook", RequestNamespace="http://us_minhquang.com/", ResponseNamespace="http://us_minhquang.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SachDTO[] getListBook() {
            object[] results = this.Invoke("getListBook", new object[0]);
            return ((SachDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void getListBookAsync() {
            this.getListBookAsync(null);
        }
        
        /// <remarks/>
        public void getListBookAsync(object userState) {
            if ((this.getListBookOperationCompleted == null)) {
                this.getListBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetListBookOperationCompleted);
            }
            this.InvokeAsync("getListBook", new object[0], this.getListBookOperationCompleted, userState);
        }
        
        private void OngetListBookOperationCompleted(object arg) {
            if ((this.getListBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getListBookCompleted(this, new getListBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://us_minhquang.com/")]
    public partial class SachDTO {
        
        private string dongGiaField;
        
        private string soLuongField;
        
        private string tenSachField;
        
        private string maSachField;
        
        /// <remarks/>
        public string DongGia {
            get {
                return this.dongGiaField;
            }
            set {
                this.dongGiaField = value;
            }
        }
        
        /// <remarks/>
        public string SoLuong {
            get {
                return this.soLuongField;
            }
            set {
                this.soLuongField = value;
            }
        }
        
        /// <remarks/>
        public string TenSach {
            get {
                return this.tenSachField;
            }
            set {
                this.tenSachField = value;
            }
        }
        
        /// <remarks/>
        public string MaSach {
            get {
                return this.maSachField;
            }
            set {
                this.maSachField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void addBookCompletedEventHandler(object sender, addBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void updateBookCompletedEventHandler(object sender, updateBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void deleteBookCompletedEventHandler(object sender, deleteBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void searchBookCompletedEventHandler(object sender, searchBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SachDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SachDTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getListBookCompletedEventHandler(object sender, getListBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getListBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getListBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SachDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SachDTO[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591