//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewLayer.NguoiDungService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NguoiDungService.INguoiDungBLL")]
    public interface INguoiDungBLL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungBLL/layDuLieu", ReplyAction="http://tempuri.org/INguoiDungBLL/layDuLieuResponse")]
        System.Data.DataSet layDuLieu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INguoiDungBLL/layDuLieu", ReplyAction="http://tempuri.org/INguoiDungBLL/layDuLieuResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> layDuLieuAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INguoiDungBLLChannel : ViewLayer.NguoiDungService.INguoiDungBLL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NguoiDungBLLClient : System.ServiceModel.ClientBase<ViewLayer.NguoiDungService.INguoiDungBLL>, ViewLayer.NguoiDungService.INguoiDungBLL {
        
        public NguoiDungBLLClient() {
        }
        
        public NguoiDungBLLClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NguoiDungBLLClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguoiDungBLLClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NguoiDungBLLClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet layDuLieu() {
            return base.Channel.layDuLieu();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> layDuLieuAsync() {
            return base.Channel.layDuLieuAsync();
        }
    }
}
