<?xml version="1.0" encoding="utf-8"?><Database Name="DBShopping" Class="ShoppingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MINH_QUANG\SQLEXPRESS;Initial Catalog=DBShopping;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DBShoppingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CateID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Products" ThisKey="CateID" OtherKey="CateID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quanlity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalMoney" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CateID" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Category_Product" Member="Category" ThisKey="CateID" OtherKey="CateID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>